server:
  port: 8080
spring:
  application:
    name: F-Task
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    url: ${SWAGGER_CONFIG_URL:/v3/api-docs}
    persistAuthorization: true


jwt:
  SIGNER_KEY: ${SIGNER_KEY}

speedSMS:
  token: ${SPSMS_TOKEN}

infobip:
  api: ${INFOBIP_API}
  url: ${INFOBIP_URL}
  sender: InfoSMS

firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  client-id: ${FIREBASE_CLIENT_ID}

firestore:
  type: ${FIRESTORE_TYPE}
  project-id: ${FIRESTORE_PROJECT_ID}
  private-key-id: ${FIRESTORE_PRIVATE_KEY_ID}
  private-key: ${FIRESTORE_PRIVATE_KEY}
  client-email: ${FIRESTORE_CLIENT_EMAIL}
  client-id: ${FIRESTORE_CLIENT_ID}
  auth-url: ${FIRESTORE_AUTH_URI}
  token-uri: ${FIRESTORE_TOKEN_URI}
  auth-cert-url: ${FIRESTORE_AUTH_PROVIDER_X509_CERT_URL}
  client-cert-url : ${FIRESTORE_CLIENT_X509_CERT_URL}
  universe-domain: ${FIRESTORE_UNIVERSE_DOMAIN}

vnpay:
  code: ${VNPAY_CODE}
  hash_secret: ${VNPAY_HASH_SECRET}
  url: ${VNPAY_URL}
  return: ${VNPAY_RETURN}
