server:
  port: 8080
spring:
  application:
    name: F-Task
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

springdoc:
  api-docs:
    path: /v3/api-docs/
  swagger-ui:
    path: /swagger
    config-url: /api/v3/api-docs/swagger-config
    persist-authorization: true

jwt:
  SIGNER_KEY: ${SIGNER_KEY}

speedSMS:
  token: ${SPSMS_TOKEN}

