package com.anhtu.ftaskbackend.enums;

public enum NotificationType {

    JOB_ACCEPTED, JOB_STARTED, JOB_COMPLETED, NEW_JOB_AVAILABLE, PAYMENT_SUCCESS, PAYMENT_FAILED, PAYMENT_CREATED, 
    PARTNER_CANCELLED_CLAIM, EARNING_RECEIVED, REVIEW_RECEIVED, BOOKING_CREATED, INSUFFICIENT_PARTNERS_WARNING

}
